// Wraps the OpenNext worker. With inline CSS, Next.js streams its legacy-browser (nomodule) script
// before <!DOCTYPE html>, which puts browsers into quirks mode. Move that tag into <head>.
// @ts-expect-error -- generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

// @ts-expect-error -- generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

const worker = {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    const response: Response = await handler.fetch(request, env, ctx);
    if (!response.headers.get("content-type")?.includes("text/html")) return response;
    const moved: string[] = [];
    return new HTMLRewriter()
      .on("script[nomodule]", {
        element(script) {
          const src = script.getAttribute("src");
          if (!src) return;
          moved.push(`<script src="${src}" nomodule></script>`);
          script.remove();
        },
      })
      .on("head", {
        element(head) {
          head.onEndTag(end => {
            for (const tag of moved.splice(0)) end.before(tag, { html: true });
          });
        },
      })
      .transform(response);
  },
};

export default worker;
