// Wraps the OpenNext worker.
// 1. With inline CSS, Next.js streams its legacy-browser (nomodule) script before <!DOCTYPE html>, which puts
//    browsers into quirks mode. Move that tag into <head>.
// 2. Page HTML is the same for every visitor (sign-in lives in the browser), so keep a copy at the edge for a short
//    time. Repeat visits then skip server rendering and its CPU cost.
// @ts-expect-error -- generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

// @ts-expect-error -- generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

const EDGE_TTL_SECONDS = 60;

type Env = { CF_VERSION_METADATA?: { id: string } };

function edgeCacheKey(request: Request, env: Env): Request | null {
  if (request.method !== "GET") return null;
  const url = new URL(request.url);
  if (url.pathname.startsWith("/api/") || url.pathname.startsWith("/_next/") || url.searchParams.has("_rsc")) return null;
  const headers = request.headers;
  if (headers.has("rsc") || headers.has("next-action") || headers.has("next-router-prefetch") || headers.has("authorization")) return null;
  if (!headers.get("accept")?.includes("text/html")) return null;
  // A new deployment gets new asset names, so it must never receive HTML cached by the previous one.
  url.searchParams.set("__deployment", env.CF_VERSION_METADATA?.id ?? "local");
  return new Request(url.toString(), { method: "GET" });
}

function moveNoModuleScript(response: Response): Response {
  const moved: string[] = [];
  return new HTMLRewriter()
    .on("script[nomodule]", {
      element(script) {
        const src = script.getAttribute("src");
        if (!src) return;
        moved.push(`<script src="${src}" nomodule></script>`);
        script.remove();
      },
    })
    .on("head", {
      element(head) {
        head.onEndTag(end => {
          for (const tag of moved.splice(0)) end.before(tag, { html: true });
        });
      },
    })
    .transform(response);
}

const worker = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const cache = (caches as unknown as { default: Cache }).default;
    const key = edgeCacheKey(request, env);
    if (key) {
      const cached = await cache.match(key);
      if (cached) {
        const hit = new Response(cached.body, cached);
        hit.headers.set("Cache-Control", "private, no-cache, no-store, max-age=0, must-revalidate");
        hit.headers.set("X-Edge-Cache", "HIT");
        return hit;
      }
    }

    const response: Response = await handler.fetch(request, env, ctx);
    if (!response.headers.get("content-type")?.includes("text/html")) return response;
    const page = moveNoModuleScript(response);
    if (!key || page.status !== 200 || page.headers.has("set-cookie") || !page.body) return page;

    const [forVisitor, forCache] = page.body.tee();
    const stored = new Response(forCache, page);
    stored.headers.set("Cache-Control", `public, max-age=${EDGE_TTL_SECONDS}`);
    ctx.waitUntil(cache.put(key, stored));
    const sent = new Response(forVisitor, page);
    sent.headers.set("X-Edge-Cache", "MISS");
    return sent;
  },
};

export default worker;
