'use client';
import { useState } from 'react';
import { Building, Building2, Check, DoorOpen, Home, Hotel, Pencil, ShieldCheck } from 'lucide-react';
import type { Amenity, Category, PropertyType, RoomType } from '@/types/api';
import { Modal } from '@/components/ui/modal';
import { Stepper } from '@/components/ui/stepper';
import { AppImage as Image } from '@/components/ui/app-image';
import { formatPrice, plural } from '@/lib/format';
import { PhotoStep } from './photo-step';
import { HostAddressPicker } from '@/components/maps';
import type { Draft } from './form-model';
import styles from './listing-form.module.css';

const propertyOptions: { value: PropertyType; label: string; Icon: typeof Home }[] = [{ value: 'house', label: 'House', Icon: Home }, { value: 'apartment', label: 'Apartment', Icon: Building2 }, { value: 'guesthouse', label: 'Guesthouse', Icon: Building }, { value: 'hotel', label: 'Hotel', Icon: Hotel }];
const roomOptions: { value: RoomType; label: string; description: string; Icon: typeof Home }[] = [{ value: 'entire_home', label: 'An entire place', description: 'Guests have the whole place to themselves.', Icon: Home }, { value: 'private_room', label: 'A room', description: 'Guests have their own room, plus access to shared spaces.', Icon: DoorOpen }, { value: 'shared_room', label: 'A shared room', description: 'Guests sleep in a room they may share with others.', Icon: Building2 }];
export function Intro() { return <div className={styles.intro}><div><h1>It’s easy to get started on Airbnb</h1></div><ol>{[{ title: 'Tell us about your place', text: 'Share some basic info, like where it is and how many guests can stay.', Icon: Home }, { title: 'Make it stand out', text: 'Add photos, a title and a description that show what makes your place special.', Icon: Pencil }, { title: 'Finish up and publish', text: 'Choose a starting price and review your listing before publishing.', Icon: Check }].map(({ title, text, Icon }, index) => <li key={title}><span>{index + 1}</span><div><h2>{title}</h2><p>{text}</p></div><Icon size={48} aria-hidden="true" /></li>)}</ol></div>; }
export function FormSteps({ step, draft, patch, amenities, categories, onBusyChange }: { step: number; draft: Draft; patch: (patch: Partial<Draft>) => void; amenities: Amenity[]; categories: Category[]; onBusyChange: (busy: boolean) => void }) {
  if (step === 1) return <div className={styles.tiles}>{propertyOptions.map(({ value, label, Icon }) => <button type="button" aria-pressed={draft.property_type === value} key={value} className={`${styles.tile} ${draft.property_type === value ? styles.selected : ''}`} onClick={() => patch({ property_type: value })}><Icon size={32} aria-hidden="true" />{label}</button>)}</div>;
  if (step === 2) return <div className={styles.roomRows}>{roomOptions.map(({ value, label, description, Icon }) => <button type="button" aria-pressed={draft.room_type === value} key={value} className={`${styles.roomRow} ${draft.room_type === value ? styles.selected : ''}`} onClick={() => patch({ room_type: value })}><span><strong>{label}</strong><span>{description}</span></span><Icon size={32} aria-hidden="true" /></button>)}</div>;
  if (step === 3) return <HostAddressPicker value={{ address: draft.address, neighbourhood: draft.neighbourhood, city: draft.city, country: draft.country, latitude: draft.latitude === "" ? null : Number(draft.latitude), longitude: draft.longitude === "" ? null : Number(draft.longitude), google_place_id: draft.google_place_id }} onChange={value => patch({ ...value, latitude: value.latitude === null ? "" : String(value.latitude), longitude: value.longitude === null ? "" : String(value.longitude) })} />;
  if (step === 4) return <div>{([{ key: 'max_guests', label: 'Guests', min: 1, max: 16 }, { key: 'bedrooms', label: 'Bedrooms', min: 0, max: 50 }, { key: 'beds', label: 'Beds', min: 1, max: 50 }, { key: 'bathrooms', label: 'Bathrooms', min: 0, max: 50 }] as const).map(({ key, label, min, max }) => <div className={styles.stepperRow} key={key}><span>{label}</span><Stepper label={label.toLowerCase()} value={draft[key]} min={min} max={max} step={key === 'bathrooms' ? 0.5 : 1} onChange={value => patch({ [key]: value })} /></div>)}</div>;
  if (step === 5) return <div><div className={styles.tiles}>{amenities.map(item => <button type="button" key={item.id} aria-pressed={draft.amenity_ids.includes(item.id)} className={`${styles.tile} ${draft.amenity_ids.includes(item.id) ? styles.selected : ''}`} onClick={() => patch({ amenity_ids: draft.amenity_ids.includes(item.id) ? draft.amenity_ids.filter(id => id !== item.id) : [...draft.amenity_ids, item.id] })}><Check size={24} aria-hidden="true" />{item.name}</button>)}</div><h2 className={styles.categoryTitle}>How would you describe your place?</h2><p className="muted">Choose any categories that fit. These help guests find your listing.</p><div className={styles.chips}>{categories.map(item => <button type="button" key={item.id} className={draft.category_ids.includes(item.id) ? styles.selected : ''} aria-pressed={draft.category_ids.includes(item.id)} onClick={() => patch({ category_ids: draft.category_ids.includes(item.id) ? draft.category_ids.filter(id => id !== item.id) : [...draft.category_ids, item.id] })}>{item.name}</button>)}</div></div>;
  if (step === 6) return <PhotoStep photos={draft.image_urls} onChange={image_urls => patch({ image_urls })} onBusyChange={onBusyChange} />;
  if (step === 7 || step === 8) { const key = step === 7 ? 'title' : 'description', max = step === 7 ? 120 : 5000; return <label className={styles.textareaLabel}>{step === 7 ? 'Listing title' : 'Listing description'}<textarea autoFocus maxLength={max} rows={step === 7 ? 4 : 7} className={step === 7 ? styles.titleInput : styles.descriptionInput} value={draft[key]} onChange={event => patch({ [key]: event.target.value })} /><span className="muted small" aria-live="polite">{draft[key].length} / {max.toLocaleString()} characters</span></label>; }
  if (step === 9) return <div><div className={styles.priceInput}><span>₹</span><input aria-label="Price per night" style={draft.price_per_night >= 100000 ? { fontSize: 40 } : undefined} type="number" min="1" max="1000000" step="1" value={draft.price_per_night || ''} onChange={event => patch({ price_per_night: Number(event.target.value) })} /><Pencil size={24} aria-hidden="true" /></div><p className={styles.priceCaption}>Nightly price before fees {formatPrice(draft.price_per_night || 0)}</p><label className={styles.field}>Cleaning fee (INR)<input type="number" min="0" max="100000" step="1" value={draft.cleaning_fee} onChange={event => patch({ cleaning_fee: Number(event.target.value) })} /></label><p className="muted small">The service fee and final guest total are calculated when guests choose their travel dates.</p></div>;
  if (step === 10) return <ReviewStep draft={draft} amenities={amenities} />;
  return null;
}
function ReviewStep({ draft, amenities }: { draft: Draft; amenities: Amenity[] }) {
  const [preview, setPreview] = useState(false);
  return <div><div className={styles.previewCard}><div className={styles.previewImage}>{draft.image_urls[0] && <Image src={draft.image_urls[0]} alt={`Cover of ${draft.title}`} fill sizes="(max-width: 744px) 90vw, 630px" />}</div><div><h2>{draft.title}</h2><p>{draft.city}, {draft.country}</p><p><strong>{formatPrice(draft.price_per_night)}</strong> night</p><button type="button" className="text-button" onClick={() => setPreview(true)}>Show preview</button></div></div><h2 className={styles.categoryTitle}>What’s next?</h2><div className={styles.nextRow}><ShieldCheck size={32} aria-hidden="true" /><div><h3>Your listing is ready to welcome guests</h3><p>You can update your place, photos and price from your host dashboard at any time.</p></div></div><Modal open={preview} onClose={() => setPreview(false)} title="Your listing preview" width={780}><div className={styles.previewModal}><h2>{draft.title}</h2><div className={styles.previewImage}>{draft.image_urls[0] && <Image src={draft.image_urls[0]} alt={draft.title} fill sizes="(max-width: 744px) 90vw, 720px" />}</div><h3>{roomOptions.find(item => item.value === draft.room_type)?.label} in {draft.city}, {draft.country}</h3><p>{plural(draft.max_guests, 'guest')} · {plural(draft.bedrooms, 'bedroom')} · {plural(draft.beds, 'bed')} · {plural(draft.bathrooms, 'bathroom')}</p><p style={{ whiteSpace: 'pre-line' }}>{draft.description}</p><h3>What this place offers</h3><p>{amenities.filter(item => draft.amenity_ids.includes(item.id)).map(item => item.name).join(' · ') || 'No amenities selected'}</p><strong>{formatPrice(draft.price_per_night)} night</strong></div></Modal></div>;
}




