'use client';
import { useState, useSyncExternalStore } from 'react';
import { toast } from 'sonner';
import { AirVent, Building, Building2, CookingPot, DoorOpen, Home, Hotel, KeyRound, ParkingCircle, Pencil, Search, ShieldCheck, Tv, WashingMachine, Waves, Wifi } from 'lucide-react';
import type { Amenity, Category, PropertyType, RoomType } from '@/types/api';
import { Modal } from '@/components/ui/modal';
import { Stepper } from '@/components/ui/stepper';
import { AppImage as Image } from '@/components/ui/app-image';
import { formatPrice, plural } from '@/lib/format';
import { PhotoStep } from './photo-step';
import { HostAddressPicker } from '@/components/maps';
import type { Draft } from './form-model';
import styles from './listing-form.module.css';

const propertyOptions: { value: PropertyType; label: string; Icon: typeof Home }[] = [{ value: 'house', label: 'House', Icon: Home }, { value: 'apartment', label: 'Apartment', Icon: Building2 }, { value: 'guesthouse', label: 'Guesthouse', Icon: Building }, { value: 'hotel', label: 'Hotel', Icon: Hotel }];
const roomOptions: { value: RoomType; label: string; description: string; Icon: typeof Home }[] = [{ value: 'entire_home', label: 'An entire place', description: 'Guests have the whole place to themselves.', Icon: Home }, { value: 'private_room', label: 'A room', description: 'Guests have their own room, plus access to shared spaces.', Icon: DoorOpen }, { value: 'shared_room', label: 'A shared room', description: 'Guests sleep in a room they may share with others.', Icon: Building2 }];
const subscribeMotion=(listener:()=>void)=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");media.addEventListener("change",listener);return()=>media.removeEventListener("change",listener);};
const reducedMotionSnapshot=()=>window.matchMedia("(prefers-reduced-motion: reduce)").matches;
export function Intro({draft,patch,onContinue}: {draft:Draft;patch:(value:Partial<Draft>)=>void;onContinue:()=>void}) {
  const reducedMotion=useSyncExternalStore(subscribeMotion,reducedMotionSnapshot,()=>true);
  return <div className={styles.entry}><div className={styles.entryCopy}><h1>Set up your Airbnb listing</h1><p>It’s easy to create a great listing – let’s start with your address.</p><div className={styles.entryAddress}><Search className={styles.entrySearchIcon} size={18} strokeWidth={1.5} aria-hidden="true"/><HostAddressPicker searchOnly placeholder="Enter your address" value={{address:draft.address,neighbourhood:draft.neighbourhood,city:draft.city,country:draft.country,latitude:draft.latitude === "" ? null : Number(draft.latitude),longitude:draft.longitude === "" ? null : Number(draft.longitude),google_place_id:draft.google_place_id}} onChange={value=>{patch({...value,latitude:value.latitude===null?"":String(value.latitude),longitude:value.longitude===null?"":String(value.longitude)});if(value.latitude!==null&&value.longitude!==null)onContinue();}}/></div><p className={styles.entryOther}>Not listing a home? Host an <button type="button" onClick={()=>toast('Experiences and services are coming soon')}>experience or service</button>.</p><button type="button" className={`text-button ${styles.entryManual}`} onClick={onContinue}>Enter address manually</button></div><div className={styles.entryVisual}>{!reducedMotion?<video autoPlay muted playsInline preload="metadata" poster="https://a0.muscache.com/im/mux/kgtTVz6YLZr5AordFq1LiR2CI8E00x1lw02frByOeHvaY/thumbnail.jpg?time=0.0" aria-label="A tour of welcoming homes"><source src="https://stream.media.muscache.com/mp4/BS9QgsDQIFvRdMk00NihVJ4awIr4gQqKanLfnWOiM4I8.mp4?v_res=480p" type="video/mp4"/></video>:<Image src="https://a0.muscache.com/im/mux/kgtTVz6YLZr5AordFq1LiR2CI8E00x1lw02frByOeHvaY/thumbnail.jpg?time=0.0" alt="Colourful homes along a tree-lined street" fill sizes="(max-width:743px) 100vw, 45vw" loading="eager" fetchPriority="high" unoptimized/>}</div></div>;
}
export function FormSteps({ step, draft, patch, amenities, categories, onBusyChange }: { step: number; draft: Draft; patch: (patch: Partial<Draft>) => void; amenities: Amenity[]; categories: Category[]; onBusyChange: (busy: boolean) => void }) {
  if (step === 1) return <div className={styles.tiles}>{propertyOptions.map(({ value, label, Icon }) => <button type="button" aria-pressed={draft.property_type === value} key={value} className={`${styles.tile} ${draft.property_type === value ? styles.selected : ''}`} onClick={() => patch({ property_type: value })}><Icon size={32} aria-hidden="true" />{label}</button>)}</div>;
  if (step === 2) return <div className={styles.roomRows}>{roomOptions.map(({ value, label, description, Icon }) => <button type="button" aria-pressed={draft.room_type === value} key={value} className={`${styles.roomRow} ${draft.room_type === value ? styles.selected : ''}`} onClick={() => patch({ room_type: value })}><span><strong>{label}</strong><span>{description}</span></span><Icon size={32} aria-hidden="true" /></button>)}</div>;
  if (step === 3) return <HostAddressPicker value={{ address: draft.address, neighbourhood: draft.neighbourhood, city: draft.city, country: draft.country, latitude: draft.latitude === "" ? null : Number(draft.latitude), longitude: draft.longitude === "" ? null : Number(draft.longitude), google_place_id: draft.google_place_id }} onChange={value => patch({ ...value, latitude: value.latitude === null ? "" : String(value.latitude), longitude: value.longitude === null ? "" : String(value.longitude) })} />;
  if (step === 4) return <div>{([{ key: 'max_guests', label: 'Guests', min: 1, max: 16 }, { key: 'bedrooms', label: 'Bedrooms', min: 0, max: 50 }, { key: 'beds', label: 'Beds', min: 1, max: 50 }, { key: 'bathrooms', label: 'Bathrooms', min: 0, max: 50 }] as const).map(({ key, label, min, max }) => <div className={styles.stepperRow} key={key}><span>{label}</span><Stepper label={label.toLowerCase()} value={draft[key]} min={min} max={max} step={key === 'bathrooms' ? 0.5 : 1} onChange={value => patch({ [key]: value })} /></div>)}</div>;
  if (step === 5) return <div><div className={styles.tiles}>{amenities.map(item => <button type="button" key={item.id} aria-pressed={draft.amenity_ids.includes(item.id)} className={`${styles.tile} ${draft.amenity_ids.includes(item.id) ? styles.selected : ''}`} onClick={() => patch({ amenity_ids: draft.amenity_ids.includes(item.id) ? draft.amenity_ids.filter(id => id !== item.id) : [...draft.amenity_ids, item.id] })}>{(() => { const Icon=({wifi:Wifi,"air-conditioning":AirVent,kitchen:CookingPot,pool:Waves,"washing-machine":WashingMachine,tv:Tv,"free-parking":ParkingCircle,"self-check-in":KeyRound} as Record<string,typeof Home>)[item.icon]??Home; return <Icon size={32} strokeWidth={1.5} aria-hidden="true"/>; })()}{item.name}</button>)}</div><h2 className={styles.categoryTitle}>How would you describe your place?</h2><p className="muted">Choose any categories that fit. These help guests find your listing.</p><div className={styles.chips}>{categories.map(item => <button type="button" key={item.id} className={draft.category_ids.includes(item.id) ? styles.selected : ''} aria-pressed={draft.category_ids.includes(item.id)} onClick={() => patch({ category_ids: draft.category_ids.includes(item.id) ? draft.category_ids.filter(id => id !== item.id) : [...draft.category_ids, item.id] })}>{item.name}</button>)}</div></div>;
  if (step === 6) return <PhotoStep photos={draft.image_urls} onChange={image_urls => patch({ image_urls })} onBusyChange={onBusyChange} />;
  if (step === 7 || step === 8) { const key = step === 7 ? 'title' : 'description', max = step === 7 ? 120 : 5000; return <label className={styles.textareaLabel}>{step === 7 ? 'Listing title' : 'Listing description'}<textarea aria-label={step === 7 ? "Listing title" : "Listing description"} maxLength={max} rows={step === 7 ? 4 : 7} className={step === 7 ? styles.titleInput : styles.descriptionInput} value={draft[key]} onChange={event => patch({ [key]: event.target.value })} /><span className="muted small" aria-live="polite">{draft[key].length} / {max.toLocaleString()} characters</span></label>; }
  if (step === 9) return <div><div className={styles.priceInput}><span>₹</span><input aria-label="Price per night" style={draft.price_per_night >= 100000 ? { fontSize: 40 } : undefined} type="number" min="1" max="1000000" step="1" value={draft.price_per_night || ''} onChange={event => patch({ price_per_night: Number(event.target.value) })} /><Pencil size={24} aria-hidden="true" /></div><p className={styles.priceCaption}>Nightly price before fees {formatPrice(draft.price_per_night || 0)}</p><label className={styles.field}>Cleaning fee (INR)<input type="number" min="0" max="100000" step="1" value={draft.cleaning_fee} onChange={event => patch({ cleaning_fee: Number(event.target.value) })} /></label><p className="muted small">The service fee and final guest total are calculated when guests choose their travel dates.</p><section className={styles.priceSettings} aria-labelledby="weekly-discount-heading"><h2 id="weekly-discount-heading">Discounts</h2><div className={styles.stepperRow}><div><strong>Weekly discount</strong><p>For stays of 7 nights or more</p></div><div className={styles.percentStepper}><Stepper label="weekly discount percentage" value={draft.weekly_discount_percent} min={0} max={90} onChange={weekly_discount_percent => patch({ weekly_discount_percent })} /><span aria-hidden="true">%</span></div></div></section><section className={styles.priceSettings} aria-labelledby="trip-length-heading"><h2 id="trip-length-heading">Trip length</h2><div className={styles.stepperRow}><span>Minimum nights</span><Stepper label="minimum nights" value={draft.min_nights} min={1} max={365} onChange={min_nights => patch({ min_nights, max_nights: Math.max(min_nights, draft.max_nights) })} /></div><div className={styles.stepperRow}><span>Maximum nights</span><Stepper label="maximum nights" value={draft.max_nights} min={draft.min_nights} max={365} onChange={max_nights => patch({ max_nights })} /></div></section></div>;
  if (step === 10) return <ReviewStep draft={draft} amenities={amenities} />;
  return null;
}
function ReviewStep({ draft, amenities }: { draft: Draft; amenities: Amenity[] }) {
  const [preview, setPreview] = useState(false);
  return <div><div className={styles.previewCard}><div className={styles.previewImage}>{draft.image_urls[0] && <Image src={draft.image_urls[0]} alt={`Cover of ${draft.title}`} fill sizes="(max-width: 744px) 90vw, 630px" />}</div><div><h2>{draft.title}</h2><p>{draft.city}, {draft.country}</p><p><strong>{formatPrice(draft.price_per_night)}</strong> night</p><button type="button" className="text-button" onClick={() => setPreview(true)}>Show preview</button></div></div><h2 className={styles.categoryTitle}>What’s next?</h2><div className={styles.nextRow}><ShieldCheck size={32} aria-hidden="true" /><div><h3>Your listing is ready to welcome guests</h3><p>You can update your place, photos and price from your host dashboard at any time.</p></div></div><Modal open={preview} onClose={() => setPreview(false)} title="Your listing preview" width={780}><div className={styles.previewModal}><h2>{draft.title}</h2><div className={styles.previewImage}>{draft.image_urls[0] && <Image src={draft.image_urls[0]} alt={draft.title} fill sizes="(max-width: 744px) 90vw, 720px" />}</div><h3>{roomOptions.find(item => item.value === draft.room_type)?.label} in {draft.city}, {draft.country}</h3><p>{plural(draft.max_guests, 'guest')} · {plural(draft.bedrooms, 'bedroom')} · {plural(draft.beds, 'bed')} · {plural(draft.bathrooms, 'bathroom')}</p><p style={{ whiteSpace: 'pre-line' }}>{draft.description}</p><h3>What this place offers</h3><p>{amenities.filter(item => draft.amenity_ids.includes(item.id)).map(item => item.name).join(' · ') || 'No amenities selected'}</p><strong>{formatPrice(draft.price_per_night)} night</strong></div></Modal></div>;
}




