from dataclasses import dataclass

from app.models import PropertyType, RoomType

AMENITIES = [
    ("Wifi", "wifi"),
    ("Kitchen", "kitchen"),
    ("Washer", "washer"),
    ("Dryer", "dryer"),
    ("Air conditioning", "air-conditioning"),
    ("Heating", "heating"),
    ("Dedicated workspace", "workspace"),
    ("TV", "tv"),
    ("Hair dryer", "hair-dryer"),
    ("Iron", "iron"),
    ("Pool", "pool"),
    ("Hot tub", "hot-tub"),
    ("Free parking on premises", "parking"),
    ("EV charger", "ev-charger"),
    ("Gym", "gym"),
    ("BBQ grill", "bbq"),
    ("Breakfast", "breakfast"),
    ("Indoor fireplace", "fireplace"),
    ("Beach access", "beach"),
    ("Lake access", "lake"),
    ("Ski-in/Ski-out", "ski"),
    ("Patio or balcony", "balcony"),
    ("Garden", "garden"),
    ("Self check-in", "self-check-in"),
    ("Coffee maker", "coffee"),
    ("Smoke alarm", "smoke-alarm"),
    ("Carbon monoxide alarm", "carbon-monoxide-alarm"),
]

BASE_AMENITIES = ["Wifi", "Kitchen", "Smoke alarm", "Carbon monoxide alarm", "Hair dryer"]

CATEGORIES = [
    ("amazing-views", "Amazing views", "mountain-view"),
    ("beachfront", "Beachfront", "beach"),
    ("cabins", "Cabins", "cabin"),
    ("iconic-cities", "Iconic cities", "city"),
    ("amazing-pools", "Amazing pools", "pool"),
    ("countryside", "Countryside", "countryside"),
    ("tropical", "Tropical", "palm-tree"),
    ("lakefront", "Lakefront", "lake"),
    ("design", "Design", "design"),
    ("mansions", "Mansions", "mansion"),
    ("omg", "OMG!", "ufo"),
    ("skiing", "Skiing", "ski"),
    ("tiny-homes", "Tiny homes", "tiny-home"),
    ("trending", "Trending", "trending"),
]

UNSPLASH = "https://images.unsplash.com/photo-{}?auto=format&fit=crop&w=1200&q=80"

PHOTOS = {
    "villa": [
        "1564013799919-ab600027ffc6",
        "1600596542815-ffad4c1539a9",
        "1512917774080-9991f1c4c750",
        "1613490493576-7fde63acd811",
        "1580587771525-78b9dba3b914",
        "1602343168117-bb8ffe3e2e9f",
        "1613977257363-707ba9348227",
        "1416331108676-a22ccb276e35",
    ],
    "modern": [
        "1600585154340-be6161a56a0c",
        "1600566753190-17f0baa2a6c3",
        "1600047509807-ba8f99d2cdde",
        "1494526585095-c41746248156",
        "1523217582562-09d0def993a6",
        "1600585154526-990dced4db0d",
        "1600563438938-a9a27216b4f5",
        "1600573472550-8090b5e0745e",
    ],
    "classic": [
        "1568605114967-8130f3a36994",
        "1570129477492-45c003edd2be",
        "1583608205776-bfd35f0d9f83",
        "1576941089067-2de3c901e126",
        "1572120360610-d971b9d7767c",
        "1605276374104-dee2a0ed3cd6",
        "1475855581690-80accde3ae2b",
        "1464146072230-91cabc968266",
        "1505843513577-22bb7d21e455",
        "1430285561322-7808604715df",
    ],
    "cabin": [
        "1449158743715-0a90ebb6d2d8",
        "1510798831971-661eb04b3739",
        "1518780664697-55e3ad937233",
        "1542718610-a1d656d1884c",
        "1587061949409-02df41d5e562",
        "1595877244574-e90ce41ce089",
    ],
    "tropical": [
        "1499793983690-e29da59ef1c2",
        "1520483601560-389dff434fdf",
        "1520250497591-112f2f40a3f4",
    ],
    "resort": [
        "1542314831-068cd1dbfeeb",
        "1571896349842-33c89424de2d",
        "1551882547-ff40c63fe5fa",
    ],
    "apartment": [
        "1515263487990-61b07816b324",
        "1574362848149-11496d93a7c7",
        "1545324418-cc1a3fa10c00",
    ],
    "dome": ["1521401830884-6c03c1c87ebb"],
    "view": ["1596394516093-501ba68a0ba6", "1445019980597-93fa8acb246c"],
    "living": [
        "1502672260266-1c1ef2d93688",
        "1522708323590-d24dbb6b0267",
        "1560448204-e02f11c3d0e2",
        "1493809842364-78817add7ffb",
        "1600607687939-ce8a6c25118c",
        "1600210492486-724fe5c67fb0",
        "1617806118233-18e1de247200",
        "1586023492125-27b2c045efd7",
        "1554995207-c18c203602cb",
        "1564078516393-cf04bd966897",
        "1600121848594-d8644e57abab",
        "1613545325278-f24b0cae1224",
        "1618221195710-dd6b41faaea6",
        "1618220179428-22790b461013",
        "1631679706909-1844bbd07221",
        "1598928506311-c55ded91a20c",
        "1604014237800-1c9102c219da",
        "1501183638710-841dd1904471",
        "1513694203232-719a280e022f",
        "1505691938895-1758d7feb511",
        "1505873242700-f289a29e1e0f",
    ],
    "bedroom": [
        "1505693416388-ac5ce068fe85",
        "1522771739844-6a9f6d5f14af",
        "1540518614846-7eded433c457",
        "1631049307264-da0ec9d70304",
        "1566665797739-1674de7a421a",
        "1582719478250-c89cae4dc85b",
        "1595526114035-0d45ed16cfbf",
        "1616594039964-ae9021a400a0",
        "1615874959474-d609969a20ed",
        "1611892440504-42a792e24d32",
        "1590490360182-c33d57733427",
        "1578683010236-d716f9a3f461",
        "1531835551805-16d864c8d311",
        "1499916078039-922301b0eb9b",
        "1586105251261-72a756497a11",
    ],
    "kitchen": [
        "1484154218962-a197022b5858",
        "1507089947368-19c1da9775ae",
        "1600489000022-c2086d79f9d4",
        "1600494603989-9650cf6ddd3d",
    ],
    "bath": [
        "1584622650111-993a426fbf0a",
        "1552321554-5fefe8c9ef14",
        "1600566752355-35792bedcfea",
    ],
}


@dataclass(frozen=True)
class PersonSeed:
    name: str
    email: str
    avatar: int
    about: str
    is_superhost: bool = False


HOSTS = [
    PersonSeed(
        "Aarav Mehta",
        "aarav@example.com",
        12,
        "Architect turned host. I love restoring old homes along the Indian coast.",
        is_superhost=True,
    ),
    PersonSeed(
        "Priya Sharma",
        "priya@example.com",
        47,
        "Mountain person, chai enthusiast and a host for eight years.",
        is_superhost=True,
    ),
    PersonSeed(
        "Lucas Martin",
        "lucas@example.com",
        14,
        "I split my time between Lisbon and Paris and host the flats I grew up in.",
    ),
    PersonSeed(
        "Sofia Rossi",
        "sofia@example.com",
        45,
        "Born on the Amalfi Coast. I help guests find the quiet side of every town.",
        is_superhost=True,
    ),
    PersonSeed(
        "Kenji Tanaka",
        "kenji@example.com",
        53,
        "Designer and traveller. My homes are built around light and calm.",
    ),
    PersonSeed(
        "Emma Walker",
        "emma@example.com",
        32,
        "Outdoors lover hosting cabins and lake houses across North America.",
    ),
]

GUESTS = [
    PersonSeed("Rohan Gupta", "rohan@example.com", 59, "Product designer who travels for food."),
    PersonSeed("Ananya Iyer", "ananya@example.com", 44, "Weekend hiker and photographer."),
    PersonSeed("Daniel Kim", "daniel@example.com", 60, "Remote engineer working from anywhere."),
    PersonSeed("Chloe Bennett", "chloe@example.com", 25, "Always planning the next beach trip."),
    PersonSeed("Arjun Nair", "arjun@example.com", 68, "Coffee, books and long train rides."),
    PersonSeed("Mia Fischer", "mia@example.com", 20, "Travelling the world one city at a time."),
]

DEMO_GUEST_EMAIL = "rohan@example.com"


@dataclass(frozen=True)
class ListingSeed:
    title: str
    summary: str
    address: str
    city: str
    country: str
    latitude: float
    longitude: float
    property_type: PropertyType
    room_type: RoomType
    exterior: str
    price: int
    cleaning_fee: int
    guests: int
    bedrooms: int
    beds: int
    bathrooms: float
    host: int
    categories: tuple[str, ...]
    amenities: tuple[str, ...] = ()


HOUSE, APARTMENT, GUESTHOUSE, HOTEL = PropertyType
ENTIRE, PRIVATE, SHARED = RoomType

LISTINGS = [
    ListingSeed(
        title="Portuguese villa with a private pool in Anjuna",
        summary="A restored 1920s villa a short walk from Anjuna beach, with a shaded pool and a "
        "verandah for slow breakfasts.",
        address="Mazal Vaddo, Anjuna",
        city="Goa",
        country="India",
        latitude=15.5733,
        longitude=73.7407,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="villa",
        price=240,
        cleaning_fee=40,
        guests=8,
        bedrooms=4,
        beds=5,
        bathrooms=4,
        host=0,
        categories=("amazing-pools", "tropical", "trending"),
        amenities=("Pool", "Air conditioning", "Garden", "Free parking on premises", "Breakfast"),
    ),
    ListingSeed(
        title="Beach shack studio steps from Palolem",
        summary="A bright studio with a hammock deck. Fall asleep to the waves and wake up to "
        "fishing boats coming in.",
        address="Palolem Beach Road",
        city="Goa",
        country="India",
        latitude=15.0100,
        longitude=74.0232,
        property_type=GUESTHOUSE,
        room_type=ENTIRE,
        exterior="tropical",
        price=65,
        cleaning_fee=10,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=0,
        categories=("beachfront", "tropical"),
        amenities=("Beach access", "Air conditioning", "Patio or balcony"),
    ),
    ListingSeed(
        title="Lake-view haveli suite in Udaipur",
        summary="Wake up to Lake Pichola from a hand-painted suite inside a 200-year-old haveli "
        "in the old city.",
        address="Gangaur Ghat Marg",
        city="Udaipur",
        country="India",
        latitude=24.5788,
        longitude=73.6836,
        property_type=HOTEL,
        room_type=PRIVATE,
        exterior="resort",
        price=120,
        cleaning_fee=0,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=0,
        categories=("amazing-views", "lakefront", "iconic-cities"),
        amenities=("Air conditioning", "Breakfast", "TV", "Patio or balcony"),
    ),
    ListingSeed(
        title="Pink City courtyard home in Jaipur",
        summary="A calm courtyard house near Hawa Mahal with block-printed linens and a rooftop "
        "for sunset chai.",
        address="Chandpol Bazaar",
        city="Jaipur",
        country="India",
        latitude=26.9239,
        longitude=75.8267,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="classic",
        price=95,
        cleaning_fee=20,
        guests=6,
        bedrooms=3,
        beds=3,
        bathrooms=2,
        host=0,
        categories=("iconic-cities", "design"),
        amenities=("Air conditioning", "Washer", "Dedicated workspace", "Patio or balcony"),
    ),
    ListingSeed(
        title="Apple orchard cabin above Old Manali",
        summary="A timber cabin among apple trees with a wood stove, snow views and a trail to "
        "the river right outside.",
        address="Old Manali Road",
        city="Manali",
        country="India",
        latitude=32.2569,
        longitude=77.1734,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="cabin",
        price=85,
        cleaning_fee=15,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=1,
        host=1,
        categories=("cabins", "amazing-views", "skiing"),
        amenities=("Indoor fireplace", "Heating", "Free parking on premises", "Garden"),
    ),
    ListingSeed(
        title="Riverside yoga retreat room in Rishikesh",
        summary="A peaceful room in a family guesthouse by the Ganges, with morning yoga on the "
        "terrace included.",
        address="Tapovan, Laxman Jhula",
        city="Rishikesh",
        country="India",
        latitude=30.1290,
        longitude=78.3260,
        property_type=GUESTHOUSE,
        room_type=PRIVATE,
        exterior="view",
        price=40,
        cleaning_fee=5,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=1,
        categories=("amazing-views", "countryside"),
        amenities=("Breakfast", "Heating", "Patio or balcony"),
    ),
    ListingSeed(
        title="Tea estate bungalow in the Munnar hills",
        summary="A colonial planter's bungalow surrounded by tea gardens, mist and birdsong.",
        address="Chithirapuram Estate",
        city="Munnar",
        country="India",
        latitude=10.0889,
        longitude=77.0595,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="classic",
        price=110,
        cleaning_fee=25,
        guests=6,
        bedrooms=3,
        beds=4,
        bathrooms=3,
        host=1,
        categories=("countryside", "amazing-views"),
        amenities=("Indoor fireplace", "Garden", "Breakfast", "Free parking on premises"),
    ),
    ListingSeed(
        title="Sea-facing apartment on Marine Drive",
        summary="A high-floor apartment with floor-to-ceiling windows over the Queen's Necklace.",
        address="Marine Drive, Churchgate",
        city="Mumbai",
        country="India",
        latitude=18.9430,
        longitude=72.8238,
        property_type=APARTMENT,
        room_type=ENTIRE,
        exterior="apartment",
        price=150,
        cleaning_fee=25,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=2,
        host=1,
        categories=("iconic-cities", "amazing-views"),
        amenities=("Air conditioning", "Gym", "Dedicated workspace", "TV", "Washer"),
    ),
    ListingSeed(
        title="Jungle villa with infinity pool in Ubud",
        summary="An open-air villa above the Ayung river valley with an infinity pool and daily "
        "Balinese breakfast.",
        address="Jalan Raya Sayan",
        city="Bali",
        country="Indonesia",
        latitude=-8.5069,
        longitude=115.2440,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="villa",
        price=210,
        cleaning_fee=35,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=2,
        host=4,
        categories=("amazing-pools", "tropical", "omg"),
        amenities=("Pool", "Air conditioning", "Breakfast", "Garden"),
    ),
    ListingSeed(
        title="Geodesic dome in the rice terraces",
        summary="Sleep under a clear dome among the Tegallalang rice terraces. Stargazing is "
        "included.",
        address="Tegallalang",
        city="Bali",
        country="Indonesia",
        latitude=-8.4344,
        longitude=115.2793,
        property_type=GUESTHOUSE,
        room_type=ENTIRE,
        exterior="dome",
        price=130,
        cleaning_fee=20,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=4,
        categories=("omg", "tropical", "tiny-homes"),
        amenities=("Breakfast", "Garden"),
    ),
    ListingSeed(
        title="Alfama loft with river views",
        summary="A sunny loft in Lisbon's oldest neighbourhood. Fado drifts up from the street at "
        "night.",
        address="Rua de São Miguel",
        city="Lisbon",
        country="Portugal",
        latitude=38.7115,
        longitude=-9.1300,
        property_type=APARTMENT,
        room_type=ENTIRE,
        exterior="apartment",
        price=135,
        cleaning_fee=30,
        guests=3,
        bedrooms=1,
        beds=2,
        bathrooms=1,
        host=2,
        categories=("iconic-cities", "design"),
        amenities=("Washer", "Dedicated workspace", "Patio or balcony", "Coffee maker"),
    ),
    ListingSeed(
        title="Haussmann apartment near the Marais",
        summary="Chevron floors, a marble fireplace and tall windows over a quiet Paris street.",
        address="Rue de Turenne",
        city="Paris",
        country="France",
        latitude=48.8590,
        longitude=2.3640,
        property_type=APARTMENT,
        room_type=ENTIRE,
        exterior="classic",
        price=260,
        cleaning_fee=45,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=1,
        host=2,
        categories=("iconic-cities", "design", "trending"),
        amenities=("Washer", "Dryer", "Dedicated workspace", "Coffee maker", "TV"),
    ),
    ListingSeed(
        title="Cosy room above a boulangerie in Montmartre",
        summary="A private room with a view of Sacré-Cœur and fresh croissants from downstairs.",
        address="Rue des Abbesses",
        city="Paris",
        country="France",
        latitude=48.8848,
        longitude=2.3370,
        property_type=APARTMENT,
        room_type=PRIVATE,
        exterior="apartment",
        price=90,
        cleaning_fee=15,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=2,
        categories=("iconic-cities",),
        amenities=("Coffee maker", "Heating"),
    ),
    ListingSeed(
        title="Cave suite with caldera views in Oia",
        summary="A whitewashed cave suite carved into the cliff, with a private plunge pool facing "
        "the sunset.",
        address="Oia Caldera Path",
        city="Santorini",
        country="Greece",
        latitude=36.4618,
        longitude=25.3753,
        property_type=HOTEL,
        room_type=ENTIRE,
        exterior="resort",
        price=420,
        cleaning_fee=50,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=3,
        categories=("amazing-views", "amazing-pools", "omg"),
        amenities=("Pool", "Hot tub", "Breakfast", "Air conditioning", "Patio or balcony"),
    ),
    ListingSeed(
        title="Lemon grove villa on the Amalfi Coast",
        summary="Terraced gardens, a pool among the lemon trees and the sea glittering below.",
        address="Via Pizzo, Praiano",
        city="Amalfi",
        country="Italy",
        latitude=40.6110,
        longitude=14.5310,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="villa",
        price=480,
        cleaning_fee=60,
        guests=10,
        bedrooms=5,
        beds=6,
        bathrooms=5,
        host=3,
        categories=("mansions", "amazing-pools", "amazing-views"),
        amenities=("Pool", "Garden", "Air conditioning", "Patio or balcony", "Breakfast"),
    ),
    ListingSeed(
        title="Fisherman's cottage in Positano",
        summary="A small blue-shuttered cottage on the steps down to Spiaggia Grande.",
        address="Via Positanesi d'America",
        city="Amalfi",
        country="Italy",
        latitude=40.6281,
        longitude=14.4850,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="classic",
        price=190,
        cleaning_fee=30,
        guests=3,
        bedrooms=1,
        beds=2,
        bathrooms=1,
        host=3,
        categories=("beachfront", "amazing-views"),
        amenities=("Beach access", "Air conditioning", "Patio or balcony"),
    ),
    ListingSeed(
        title="Modernist flat near Sagrada Família",
        summary="A design-led apartment with a sunny balcony, ten minutes from Gaudí's basilica.",
        address="Carrer de Mallorca",
        city="Barcelona",
        country="Spain",
        latitude=41.4036,
        longitude=2.1744,
        property_type=APARTMENT,
        room_type=ENTIRE,
        exterior="modern",
        price=170,
        cleaning_fee=35,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=2,
        host=2,
        categories=("iconic-cities", "design"),
        amenities=("Air conditioning", "Washer", "Dedicated workspace", "Patio or balcony"),
    ),
    ListingSeed(
        title="Treehouse cabana by the cenotes",
        summary="A raised jungle cabana with an outdoor shower, five minutes from the Tulum beach.",
        address="Carretera Tulum-Boca Paila",
        city="Tulum",
        country="Mexico",
        latitude=20.1960,
        longitude=-87.4630,
        property_type=GUESTHOUSE,
        room_type=ENTIRE,
        exterior="tropical",
        price=160,
        cleaning_fee=25,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=4,
        categories=("tropical", "omg", "beachfront"),
        amenities=("Beach access", "Breakfast", "Garden"),
    ),
    ListingSeed(
        title="Machiya townhouse in Higashiyama",
        summary="A traditional wooden townhouse with tatami rooms, a cedar bath and a moss garden.",
        address="Higashiyama Ward",
        city="Kyoto",
        country="Japan",
        latitude=34.9980,
        longitude=135.7800,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="modern",
        price=230,
        cleaning_fee=40,
        guests=5,
        bedrooms=2,
        beds=4,
        bathrooms=1.5,
        host=4,
        categories=("design", "iconic-cities"),
        amenities=("Heating", "Washer", "Garden", "Coffee maker"),
    ),
    ListingSeed(
        title="Clifftop house above Camps Bay",
        summary="Glass walls, a heated pool and the Twelve Apostles behind you.",
        address="Victoria Road, Camps Bay",
        city="Cape Town",
        country="South Africa",
        latitude=-33.9510,
        longitude=18.3770,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="modern",
        price=350,
        cleaning_fee=50,
        guests=8,
        bedrooms=4,
        beds=4,
        bathrooms=4,
        host=5,
        categories=("amazing-views", "amazing-pools", "mansions"),
        amenities=("Pool", "Gym", "Air conditioning", "Free parking on premises", "BBQ grill"),
    ),
    ListingSeed(
        title="Oceanfront glass house in Malibu",
        summary="A modern beach house on the sand with a deck over the Pacific.",
        address="Pacific Coast Highway",
        city="Malibu",
        country="United States",
        latitude=34.0360,
        longitude=-118.7020,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="modern",
        price=890,
        cleaning_fee=150,
        guests=8,
        bedrooms=4,
        beds=5,
        bathrooms=4.5,
        host=5,
        categories=("beachfront", "mansions", "trending"),
        amenities=(
            "Beach access",
            "Hot tub",
            "Free parking on premises",
            "EV charger",
            "BBQ grill",
        ),
    ),
    ListingSeed(
        title="Ski chalet with hot tub in Aspen",
        summary="A timber chalet near the Snowmass lifts with a sauna and an outdoor hot tub.",
        address="Owl Creek Road",
        city="Aspen",
        country="United States",
        latitude=39.2090,
        longitude=-106.9490,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="cabin",
        price=640,
        cleaning_fee=120,
        guests=10,
        bedrooms=5,
        beds=6,
        bathrooms=4,
        host=5,
        categories=("skiing", "cabins", "mansions"),
        amenities=("Ski-in/Ski-out", "Hot tub", "Indoor fireplace", "Heating", "Gym"),
    ),
    ListingSeed(
        title="A-frame cabin on Lake Tahoe",
        summary="A classic A-frame with a private dock, kayaks and a wood stove.",
        address="West Lake Boulevard",
        city="Lake Tahoe",
        country="United States",
        latitude=39.0968,
        longitude=-120.1600,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="cabin",
        price=310,
        cleaning_fee=70,
        guests=6,
        bedrooms=3,
        beds=4,
        bathrooms=2,
        host=5,
        categories=("lakefront", "cabins", "trending"),
        amenities=(
            "Lake access",
            "Indoor fireplace",
            "Heating",
            "BBQ grill",
            "Free parking on premises",
        ),
    ),
    ListingSeed(
        title="Loft in a converted warehouse in Brooklyn",
        summary="Exposed brick, a chef's kitchen and Manhattan views from the shared roof.",
        address="Wythe Avenue, Williamsburg",
        city="New York",
        country="United States",
        latitude=40.7210,
        longitude=-73.9600,
        property_type=APARTMENT,
        room_type=ENTIRE,
        exterior="apartment",
        price=280,
        cleaning_fee=60,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=1,
        host=2,
        categories=("iconic-cities", "design"),
        amenities=("Washer", "Dryer", "Dedicated workspace", "Gym", "Air conditioning"),
    ),
    ListingSeed(
        title="Shared room in a Lower East Side hostel",
        summary="A budget bunk in a friendly shared room with lockers and a rooftop bar.",
        address="Rivington Street",
        city="New York",
        country="United States",
        latitude=40.7200,
        longitude=-73.9880,
        property_type=HOTEL,
        room_type=SHARED,
        exterior="apartment",
        price=45,
        cleaning_fee=0,
        guests=1,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=2,
        categories=("iconic-cities",),
        amenities=("Air conditioning",),
    ),
    ListingSeed(
        title="Georgian townhouse in Notting Hill",
        summary="A pastel townhouse on a quiet mews, steps from Portobello Road market.",
        address="Portobello Road",
        city="London",
        country="United Kingdom",
        latitude=51.5150,
        longitude=-0.2050,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="classic",
        price=330,
        cleaning_fee=60,
        guests=6,
        bedrooms=3,
        beds=3,
        bathrooms=2.5,
        host=3,
        categories=("iconic-cities", "design"),
        amenities=("Washer", "Dryer", "Heating", "Garden", "Dedicated workspace"),
    ),
    ListingSeed(
        title="Thatched cottage in the Cotswolds",
        summary="A honey-stone cottage with a rose garden and a pub at the end of the lane.",
        address="Arlington Row, Bibury",
        city="Cotswolds",
        country="United Kingdom",
        latitude=51.7600,
        longitude=-1.8340,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="classic",
        price=180,
        cleaning_fee=40,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=1,
        host=3,
        categories=("countryside", "tiny-homes"),
        amenities=("Indoor fireplace", "Garden", "Heating", "Free parking on premises"),
    ),
    ListingSeed(
        title="Lakeside cabin under the Remarkables",
        summary="A cedar cabin on Lake Wakatipu with mountain views from the hot tub.",
        address="Kelvin Heights",
        city="Queenstown",
        country="New Zealand",
        latitude=-45.0450,
        longitude=168.7000,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="cabin",
        price=270,
        cleaning_fee=55,
        guests=6,
        bedrooms=3,
        beds=3,
        bathrooms=2,
        host=5,
        categories=("lakefront", "amazing-views", "skiing"),
        amenities=("Hot tub", "Lake access", "Indoor fireplace", "Heating"),
    ),
    ListingSeed(
        title="Log cabin in the Rockies near Banff",
        summary="A log cabin in the pines with elk in the meadow and a fire pit under the stars.",
        address="Tunnel Mountain Road",
        city="Banff",
        country="Canada",
        latitude=51.1784,
        longitude=-115.5500,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="cabin",
        price=220,
        cleaning_fee=45,
        guests=4,
        bedrooms=2,
        beds=3,
        bathrooms=1,
        host=5,
        categories=("cabins", "amazing-views", "skiing"),
        amenities=("Indoor fireplace", "Heating", "BBQ grill", "Free parking on premises"),
    ),
    ListingSeed(
        title="Glass cabin for the northern lights",
        summary="A minimalist cabin with a glass roof for watching the aurora from bed.",
        address="Hellisheiði",
        city="Reykjavik",
        country="Iceland",
        latitude=64.0370,
        longitude=-21.4010,
        property_type=GUESTHOUSE,
        room_type=ENTIRE,
        exterior="view",
        price=300,
        cleaning_fee=40,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=4,
        categories=("omg", "amazing-views", "tiny-homes"),
        amenities=("Hot tub", "Heating", "Free parking on premises"),
    ),
    ListingSeed(
        title="Riad with a courtyard plunge pool",
        summary="A restored riad in the medina with zellige tiles, a rooftop terrace and mint tea "
        "on arrival.",
        address="Derb Sidi Bouloukat",
        city="Marrakech",
        country="Morocco",
        latitude=31.6295,
        longitude=-7.9890,
        property_type=HOTEL,
        room_type=PRIVATE,
        exterior="villa",
        price=140,
        cleaning_fee=0,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=3,
        categories=("design", "amazing-pools"),
        amenities=("Pool", "Breakfast", "Air conditioning", "Patio or balcony"),
    ),
    ListingSeed(
        title="Beach villa with private pool in Phuket",
        summary="A Thai-style pool villa on Kamala beach with a daily housekeeper.",
        address="Kamala Beach Road",
        city="Phuket",
        country="Thailand",
        latitude=7.9500,
        longitude=98.2830,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="tropical",
        price=260,
        cleaning_fee=40,
        guests=6,
        bedrooms=3,
        beds=3,
        bathrooms=3,
        host=0,
        categories=("beachfront", "tropical", "amazing-pools"),
        amenities=("Pool", "Beach access", "Air conditioning", "Breakfast"),
    ),
    ListingSeed(
        title="Skyline apartment in Dubai Marina",
        summary="A 40th-floor apartment with a marina balcony and a rooftop infinity pool.",
        address="Al Marsa Street",
        city="Dubai",
        country="United Arab Emirates",
        latitude=25.0800,
        longitude=55.1400,
        property_type=APARTMENT,
        room_type=ENTIRE,
        exterior="apartment",
        price=230,
        cleaning_fee=50,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=2,
        host=0,
        categories=("amazing-views", "iconic-cities", "amazing-pools"),
        amenities=("Pool", "Gym", "Air conditioning", "Free parking on premises", "TV"),
    ),
    ListingSeed(
        title="Boutique hotel room in Kyoto's Gion",
        summary="A calm room with a hinoki tub, steps from the lantern-lit streets of Gion.",
        address="Hanamikoji Street",
        city="Kyoto",
        country="Japan",
        latitude=35.0030,
        longitude=135.7750,
        property_type=HOTEL,
        room_type=PRIVATE,
        exterior="resort",
        price=190,
        cleaning_fee=0,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=4,
        categories=("iconic-cities", "design"),
        amenities=("Breakfast", "Air conditioning", "TV"),
    ),
    ListingSeed(
        title="Farmhouse among vineyards in Tuscany",
        summary="A stone farmhouse with a pool, olive groves and wine tastings next door.",
        address="Strada di Montalcino",
        city="Tuscany",
        country="Italy",
        latitude=43.0580,
        longitude=11.4890,
        property_type=HOUSE,
        room_type=ENTIRE,
        exterior="villa",
        price=380,
        cleaning_fee=70,
        guests=10,
        bedrooms=5,
        beds=6,
        bathrooms=4,
        host=3,
        categories=("countryside", "amazing-pools", "mansions"),
        amenities=("Pool", "Garden", "BBQ grill", "Free parking on premises", "Indoor fireplace"),
    ),
    ListingSeed(
        title="Tiny house in the Western Ghats",
        summary="A solar-powered tiny house on a coffee farm, with a hammock and valley views.",
        address="Chikmagalur Coffee Estates",
        city="Chikmagalur",
        country="India",
        latitude=13.3161,
        longitude=75.7720,
        property_type=GUESTHOUSE,
        room_type=ENTIRE,
        exterior="cabin",
        price=55,
        cleaning_fee=10,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=1,
        categories=("tiny-homes", "countryside", "trending"),
        amenities=("Breakfast", "Garden", "Coffee maker"),
    ),
]

REVIEW_COMMENTS = [
    "Exactly like the photos. The host thought of every little detail.",
    "One of the best stays we have had. We are already planning to come back.",
    "Spotless, quiet and in a perfect location. Check-in was effortless.",
    "The views alone are worth it. Beds were very comfortable too.",
    "Great communication from the host and lots of local tips.",
    "Lovely place for a long weekend. The kitchen had everything we needed.",
    "Beautiful home with so much character. Highly recommend.",
    "Good value for the area. A little noisy at night but otherwise perfect.",
    "We loved the morning light and the coffee corner.",
    "Felt like a home, not a rental. Thank you for the warm welcome!",
    "Easy to reach, very clean and the host responded within minutes.",
    "The photos do not do it justice. Magical stay.",
]
