"""Demo seed content for Bengaluru and weekend getaways within about 250 km."""

from dataclasses import dataclass

from app.models import PropertyType, RoomType


@dataclass(frozen=True)
class PersonSeed:
    name: str
    email: str
    avatar: int
    about: str
    work: str
    languages: tuple[str, ...]
    lives_in: str
    is_superhost: bool = False
    identity_verified: bool = True


@dataclass(frozen=True)
class ListingSeed:
    title: str
    summary: str
    address: str
    neighbourhood: str
    city: str
    latitude: float
    longitude: float
    property_type: PropertyType
    room_type: RoomType
    exterior: str
    price: int
    cleaning_fee: int
    guests: int
    bedrooms: int
    beds: int
    bathrooms: float
    host: int
    categories: tuple[str, ...]
    amenities: tuple[str, ...]


HOSTS = [
    PersonSeed(
        name="Kavya Reddy",
        email="kavya@example.com",
        avatar=47,
        about="I grew up in Indiranagar and love showing guests the city I call home.",
        work="Interior designer with a small studio",
        languages=("English", "Kannada", "Telugu", "Hindi"),
        lives_in="Bengaluru, India",
        is_superhost=True,
    ),
    PersonSeed(
        name="Vikram Shetty",
        email="vikram@example.com",
        avatar=12,
        about="I spend my weekends in the hills and host the places I would want to stay in.",
        work="Engineering manager at a logistics startup",
        languages=("English", "Kannada", "Tulu", "Hindi"),
        lives_in="Bengaluru, India",
    ),
    PersonSeed(
        name="Meera Nambiar",
        email="meera@example.com",
        avatar=45,
        about="My family has grown coffee in Coorg for three generations, and I love to share it.",
        work="Coffee planter and heritage home restorer",
        languages=("English", "Kannada", "Malayalam", "Kodava"),
        lives_in="Madikeri, India",
        is_superhost=True,
    ),
    PersonSeed(
        name="Farhan Ali",
        email="farhan@example.com",
        avatar=13,
        about="I am a Frazer Town local who knows every biryani spot and every river bend nearby.",
        work="Food writer and weekend trek leader",
        languages=("English", "Urdu", "Hindi", "Kannada"),
        lives_in="Bengaluru, India",
    ),
    PersonSeed(
        name="Ishita Rao",
        email="ishita@example.com",
        avatar=44,
        about="I run a few calm, design-led stays and look after every guest like family.",
        work="Hospitality consultant",
        languages=("English", "Hindi", "Kannada", "Marathi"),
        lives_in="Bengaluru, India",
        is_superhost=True,
    ),
    PersonSeed(
        name="Nikhil Gowda",
        email="nikhil@example.com",
        avatar=53,
        about="I farm mangoes and millets outside the city and host guests who want slow days.",
        work="Organic farmer and wildlife photographer",
        languages=("English", "Kannada", "Tamil"),
        lives_in="Bengaluru, India",
    ),
]

GUESTS = [
    PersonSeed(
        name="Rohan Gupta",
        email="rohan@example.com",
        avatar=59,
        about="I travel for food, coffee and quiet places to sketch.",
        work="Product designer at a fintech startup",
        languages=("English", "Hindi"),
        lives_in="Bengaluru, India",
    ),
    PersonSeed(
        name="Ananya Iyer",
        email="ananya@example.com",
        avatar=32,
        about="I hike most weekends and always carry a camera.",
        work="Data analyst at a health-tech company",
        languages=("English", "Tamil", "Kannada"),
        lives_in="Bengaluru, India",
    ),
    PersonSeed(
        name="Neha Kapoor",
        email="neha@example.com",
        avatar=20,
        about="I plan long weekends for my friends and I take the job very seriously.",
        work="Marketing lead at a consumer brand",
        languages=("English", "Hindi", "Punjabi"),
        lives_in="Mumbai, India",
    ),
    PersonSeed(
        name="Siddharth Menon",
        email="siddharth@example.com",
        avatar=60,
        about="I work remotely and look for homes with good wifi and a good view.",
        work="Backend engineer working remotely",
        languages=("English", "Malayalam", "Hindi"),
        lives_in="Kochi, India",
    ),
    PersonSeed(
        name="Sara Thomas",
        email="sara@example.com",
        avatar=25,
        about="I love old houses, bookshops and long breakfasts.",
        work="Architecture student",
        languages=("English", "Malayalam"),
        lives_in="Chennai, India",
        identity_verified=False,
    ),
    PersonSeed(
        name="Karthik Subramanian",
        email="karthik@example.com",
        avatar=68,
        about="I take my family to a new forest or hill station every school holiday.",
        work="Chartered accountant",
        languages=("English", "Tamil", "Kannada"),
        lives_in="Bengaluru, India",
    ),
]

CATEGORIES = [
    ("amazing-views", "Amazing views", "mountain-view"),
    ("cabins", "Cabins", "cabin"),
    ("countryside", "Countryside", "countryside"),
    ("lakefront", "Lakefront", "lake"),
    ("amazing-pools", "Amazing pools", "pool"),
    ("design", "Design", "design"),
    ("trending", "Trending", "trending"),
    ("farms", "Farms", "farm"),
    ("treehouses", "Treehouses", "treehouse"),
    ("tiny-homes", "Tiny homes", "tiny-home"),
    ("omg", "OMG!", "ufo"),
    ("mansions", "Mansions", "mansion"),
    ("heritage-homes", "Heritage homes", "heritage"),
    ("iconic-cities", "Iconic cities", "city"),
]

LISTINGS = [
    ListingSeed(
        title="Sunlit design loft off 12th Main, Indiranagar",
        summary="A bright loft with handmade furniture, a reading nook and the best cafes of "
        "Indiranagar a short walk away.",
        address="12th Main Road, HAL 2nd Stage",
        neighbourhood="Indiranagar",
        city="Bengaluru",
        latitude=12.9716,
        longitude=77.6411,
        property_type=PropertyType.APARTMENT,
        room_type=RoomType.ENTIRE_HOME,
        exterior="apartment",
        price=6500,
        cleaning_fee=600,
        guests=3,
        bedrooms=1,
        beds=2,
        bathrooms=1,
        host=0,
        categories=("design", "iconic-cities"),
        amenities=(
            "Air conditioning",
            "Dedicated workspace",
            "Coffee maker",
            "Washer",
            "Self check-in",
        ),
    ),
    ListingSeed(
        title="Quiet private room in a Koramangala flat",
        summary="A calm room with its own bathroom in a plant-filled flat, close to the busy "
        "lanes of 5th Block.",
        address="17th Main Road, 5th Block",
        neighbourhood="Koramangala",
        city="Bengaluru",
        latitude=12.9348,
        longitude=77.6189,
        property_type=PropertyType.APARTMENT,
        room_type=RoomType.PRIVATE_ROOM,
        exterior="apartment",
        price=2400,
        cleaning_fee=0,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=0,
        categories=("trending",),
        amenities=("Air conditioning", "Washer", "Iron", "Patio or balcony"),
    ),
    ListingSeed(
        title="Work-friendly 1BHK in HSR Layout",
        summary="A tidy one-bedroom with a proper desk, fast wifi and a balcony that catches the "
        "evening breeze.",
        address="27th Main Road, Sector 2",
        neighbourhood="HSR Layout",
        city="Bengaluru",
        latitude=12.9121,
        longitude=77.6446,
        property_type=PropertyType.APARTMENT,
        room_type=RoomType.ENTIRE_HOME,
        exterior="apartment",
        price=3800,
        cleaning_fee=400,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=0,
        categories=("trending", "iconic-cities"),
        amenities=(
            "Dedicated workspace",
            "Air conditioning",
            "Washer",
            "Self check-in",
            "Patio or balcony",
        ),
    ),
    ListingSeed(
        title="Lake-view apartment by Ulsoor Lake",
        summary="Watch the rowing boats from a wide balcony, then walk to MG Road for dinner.",
        address="Kensington Road, Ulsoor",
        neighbourhood="Ulsoor",
        city="Bengaluru",
        latitude=12.9822,
        longitude=77.6205,
        property_type=PropertyType.APARTMENT,
        room_type=RoomType.ENTIRE_HOME,
        exterior="apartment",
        price=5200,
        cleaning_fee=500,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=2,
        host=0,
        categories=("lakefront", "amazing-views"),
        amenities=("Patio or balcony", "Air conditioning", "TV", "Gym", "Lake access"),
    ),
    ListingSeed(
        title="Pool villa in a leafy Whitefield enclave",
        summary="A four-bedroom villa with a private pool, a lawn for long lunches and room for "
        "the whole family.",
        address="Whitefield Main Road, Hope Farm",
        neighbourhood="Whitefield",
        city="Bengaluru",
        latitude=12.9789,
        longitude=77.7510,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="villa",
        price=18000,
        cleaning_fee=1500,
        guests=8,
        bedrooms=4,
        beds=5,
        bathrooms=4,
        host=0,
        categories=("amazing-pools", "trending"),
        amenities=(
            "Pool",
            "Garden",
            "Free parking on premises",
            "BBQ grill",
            "Air conditioning",
            "EV charger",
        ),
    ),
    ListingSeed(
        title="Architect's home off Sarjapur Road",
        summary="Exposed brick, a skylit courtyard and a deep sofa made for slow Sunday mornings.",
        address="Sarjapur Main Road, Kaikondrahalli",
        neighbourhood="Sarjapur Road",
        city="Bengaluru",
        latitude=12.9124,
        longitude=77.6820,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="modern",
        price=9500,
        cleaning_fee=1000,
        guests=6,
        bedrooms=3,
        beds=3,
        bathrooms=3,
        host=0,
        categories=("design",),
        amenities=(
            "Garden",
            "Dedicated workspace",
            "Free parking on premises",
            "Coffee maker",
            "Washer",
        ),
    ),
    ListingSeed(
        title="Grand Sadashivanagar mansion with a pool",
        summary="A stately home on a quiet tree-lined road, with a pool, a library and staff to "
        "help with every meal.",
        address="Palace Orchards Main Road",
        neighbourhood="Sadashivanagar",
        city="Bengaluru",
        latitude=13.0072,
        longitude=77.5802,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="villa",
        price=42000,
        cleaning_fee=4000,
        guests=12,
        bedrooms=6,
        beds=7,
        bathrooms=6.5,
        host=4,
        categories=("mansions", "amazing-pools", "iconic-cities"),
        amenities=(
            "Pool",
            "Gym",
            "Breakfast",
            "Garden",
            "Free parking on premises",
            "Air conditioning",
        ),
    ),
    ListingSeed(
        title="Heritage home on a Malleshwaram cross road",
        summary="A restored 1940s house with red oxide floors, a swing in the hall and filter "
        "coffee from the corner darshini.",
        address="8th Cross Road, Malleshwaram",
        neighbourhood="Malleshwaram",
        city="Bengaluru",
        latitude=13.0035,
        longitude=77.5710,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="classic",
        price=7500,
        cleaning_fee=800,
        guests=5,
        bedrooms=2,
        beds=3,
        bathrooms=2,
        host=2,
        categories=("heritage-homes", "iconic-cities"),
        amenities=("Garden", "Coffee maker", "Washer", "Iron"),
    ),
    ListingSeed(
        title="Courtyard room in an old Basavanagudi house",
        summary="A cool, high-ceilinged room around a sunny courtyard, a short stroll from "
        "Gandhi Bazaar.",
        address="DVG Road, Gandhi Bazaar",
        neighbourhood="Basavanagudi",
        city="Bengaluru",
        latitude=12.9450,
        longitude=77.5713,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.PRIVATE_ROOM,
        exterior="classic",
        price=2800,
        cleaning_fee=0,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=2,
        categories=("heritage-homes",),
        amenities=("Breakfast", "Garden", "Iron"),
    ),
    ListingSeed(
        title="Rooftop tiny studio in Jayanagar",
        summary="A compact studio on a terrace garden with a fold-out desk and big sunset skies.",
        address="11th Main Road, 4th Block",
        neighbourhood="Jayanagar",
        city="Bengaluru",
        latitude=12.9285,
        longitude=77.5830,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="modern",
        price=2600,
        cleaning_fee=300,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=1,
        categories=("tiny-homes", "design"),
        amenities=("Patio or balcony", "Garden", "Self check-in", "Coffee maker"),
    ),
    ListingSeed(
        title="Bungalow guest room near Mosque Road",
        summary="A large room in an old family bungalow, with famous kebab stalls just around "
        "the corner.",
        address="Mosque Road, Frazer Town",
        neighbourhood="Frazer Town",
        city="Bengaluru",
        latitude=12.9985,
        longitude=77.6167,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.PRIVATE_ROOM,
        exterior="classic",
        price=3200,
        cleaning_fee=0,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=3,
        categories=("heritage-homes", "iconic-cities"),
        amenities=("Breakfast", "Air conditioning", "Garden"),
    ),
    ListingSeed(
        title="Colonial bungalow in Richmond Town",
        summary="Tall windows, a deep verandah and a mango tree in the garden, right in the "
        "heart of the old cantonment.",
        address="Rhenius Street, Richmond Town",
        neighbourhood="Richmond Town",
        city="Bengaluru",
        latitude=12.9625,
        longitude=77.6040,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="classic",
        price=11000,
        cleaning_fee=1000,
        guests=8,
        bedrooms=4,
        beds=4,
        bathrooms=3,
        host=3,
        categories=("heritage-homes", "mansions"),
        amenities=(
            "Garden",
            "Patio or balcony",
            "Free parking on premises",
            "Washer",
            "TV",
        ),
    ),
    ListingSeed(
        title="Lakeside cottage on the Hebbal shore",
        summary="A small cottage by the water where painted storks and pelicans gather each "
        "morning.",
        address="Hebbal Lake Road, Kempapura",
        neighbourhood="Hebbal",
        city="Bengaluru",
        latitude=13.0452,
        longitude=77.5930,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="tropical",
        price=4800,
        cleaning_fee=500,
        guests=3,
        bedrooms=1,
        beds=2,
        bathrooms=1,
        host=5,
        categories=("lakefront",),
        amenities=("Lake access", "Garden", "Patio or balcony", "Coffee maker"),
    ),
    ListingSeed(
        title="Garden farmhouse with a pool near Yelahanka",
        summary="An acre of guava and papaya trees, a pool and a barbecue, only forty minutes "
        "from the airport.",
        address="Doddaballapur Road, Yelahanka",
        neighbourhood="Yelahanka",
        city="Bengaluru",
        latitude=13.1210,
        longitude=77.5720,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="villa",
        price=14000,
        cleaning_fee=1200,
        guests=10,
        bedrooms=4,
        beds=6,
        bathrooms=4,
        host=5,
        categories=("farms", "amazing-pools"),
        amenities=("Pool", "Garden", "BBQ grill", "Free parking on premises", "Breakfast"),
    ),
    ListingSeed(
        title="Family home with a terrace in JP Nagar",
        summary="A roomy duplex near parks and dosa spots, with a terrace for evening chai.",
        address="15th Cross Road, JP Nagar 6th Phase",
        neighbourhood="JP Nagar",
        city="Bengaluru",
        latitude=12.9050,
        longitude=77.5810,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="modern",
        price=6000,
        cleaning_fee=600,
        guests=6,
        bedrooms=3,
        beds=3,
        bathrooms=2.5,
        host=1,
        categories=("trending",),
        amenities=("Washer", "Patio or balcony", "Free parking on premises", "TV", "Iron"),
    ),
    ListingSeed(
        title="Bunk bed in a social hostel on 100 Feet Road",
        summary="A clean bunk with a locker and reading light, plus a common lounge full of "
        "fellow travellers.",
        address="100 Feet Road, Indiranagar",
        neighbourhood="Indiranagar",
        city="Bengaluru",
        latitude=12.9784,
        longitude=77.6408,
        property_type=PropertyType.HOTEL,
        room_type=RoomType.SHARED_ROOM,
        exterior="apartment",
        price=1200,
        cleaning_fee=0,
        guests=1,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=3,
        categories=("iconic-cities", "trending"),
        amenities=("Air conditioning", "Self check-in", "Coffee maker"),
    ),
    ListingSeed(
        title="Boutique hotel room on Lavelle Road",
        summary="A polished room with a rain shower and a breakfast terrace, close to Cubbon Park.",
        address="Lavelle Road",
        neighbourhood="Ashok Nagar",
        city="Bengaluru",
        latitude=12.9700,
        longitude=77.5965,
        property_type=PropertyType.HOTEL,
        room_type=RoomType.PRIVATE_ROOM,
        exterior="resort",
        price=8500,
        cleaning_fee=0,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=4,
        categories=("iconic-cities", "design"),
        amenities=("Breakfast", "Air conditioning", "TV", "Gym", "Iron"),
    ),
    ListingSeed(
        title="Airy 2BHK near the cafes of Kalyan Nagar",
        summary="A bright apartment with a long balcony, close to microbreweries and the "
        "airport road.",
        address="HRBR Layout 1st Block",
        neighbourhood="Kalyan Nagar",
        city="Bengaluru",
        latitude=13.0185,
        longitude=77.6395,
        property_type=PropertyType.APARTMENT,
        room_type=RoomType.ENTIRE_HOME,
        exterior="apartment",
        price=3500,
        cleaning_fee=350,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=2,
        host=1,
        categories=("trending", "iconic-cities"),
        amenities=(
            "Air conditioning",
            "Washer",
            "Dedicated workspace",
            "Patio or balcony",
            "Self check-in",
        ),
    ),
    ListingSeed(
        title="Hilltop pool villa below Nandi Hills",
        summary="Wake up above the clouds and swim with the hills in front of you, just ninety "
        "minutes from the city.",
        address="Nandi Hills Road, Karahalli",
        neighbourhood="Nandi foothills",
        city="Nandi Hills",
        latitude=13.3560,
        longitude=77.6960,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="view",
        price=12000,
        cleaning_fee=1000,
        guests=8,
        bedrooms=3,
        beds=4,
        bathrooms=3,
        host=1,
        categories=("amazing-views", "amazing-pools"),
        amenities=(
            "Pool",
            "Patio or balcony",
            "BBQ grill",
            "Free parking on premises",
            "Garden",
        ),
    ),
    ListingSeed(
        title="Stargazing dome in the Nandi foothills",
        summary="Sleep under a clear dome among vineyards and boulders, and watch the sunrise "
        "from bed.",
        address="Nandi Hills Back Road",
        neighbourhood="Muddenahalli",
        city="Nandi Hills",
        latitude=13.3920,
        longitude=77.6700,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="dome",
        price=6500,
        cleaning_fee=500,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=5,
        categories=("omg", "amazing-views"),
        amenities=("Breakfast", "Free parking on premises", "Garden", "Hot tub"),
    ),
    ListingSeed(
        title="Coffee estate cabin above Madikeri",
        summary="A timber cabin among coffee and pepper vines, with mist rolling in each "
        "evening and a fire to sit by.",
        address="Galibeedu Road",
        neighbourhood="Galibeedu",
        city="Coorg",
        latitude=12.4410,
        longitude=75.6960,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="cabin",
        price=7800,
        cleaning_fee=700,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=2,
        host=2,
        categories=("cabins", "farms"),
        amenities=(
            "Indoor fireplace",
            "Breakfast",
            "Coffee maker",
            "Free parking on premises",
            "Heating",
        ),
    ),
    ListingSeed(
        title="Treetop hideaway on a Coorg spice farm",
        summary="A raised wooden cabin in the canopy, with birdsong at dawn and a short trail "
        "to a forest stream.",
        address="Abbey Falls Road, Kaloor",
        neighbourhood="Kaloor",
        city="Coorg",
        latitude=12.4560,
        longitude=75.7150,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="cabin",
        price=9000,
        cleaning_fee=800,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=2,
        categories=("treehouses", "omg", "cabins"),
        amenities=("Breakfast", "Patio or balcony", "Coffee maker", "Heating"),
    ),
    ListingSeed(
        title="Planter's bungalow on a Chikkamagaluru estate",
        summary="A century-old estate bungalow with wide verandahs, fireplaces and guided walks "
        "through the coffee.",
        address="Aldur Road",
        neighbourhood="Aldur",
        city="Chikkamagaluru",
        latitude=13.3330,
        longitude=75.6550,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="classic",
        price=16000,
        cleaning_fee=1500,
        guests=10,
        bedrooms=5,
        beds=6,
        bathrooms=5,
        host=4,
        categories=("heritage-homes", "farms", "mansions"),
        amenities=(
            "Indoor fireplace",
            "Breakfast",
            "Garden",
            "Free parking on premises",
            "Coffee maker",
        ),
    ),
    ListingSeed(
        title="Tiny home on the road to Mullayanagiri",
        summary="A snug tiny home with a glass wall facing the Baba Budan range and a hammock on "
        "the deck.",
        address="Mullayanagiri Road, Kaimara",
        neighbourhood="Kaimara",
        city="Chikkamagaluru",
        latitude=13.3700,
        longitude=75.7360,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="cabin",
        price=3500,
        cleaning_fee=300,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=1,
        categories=("tiny-homes", "amazing-views"),
        amenities=("Patio or balcony", "Coffee maker", "Heating", "Self check-in"),
    ),
    ListingSeed(
        title="Cloud-level cottage in Kemmangundi",
        summary="A stone cottage on a ridge where the clouds drift through the garden and the "
        "valley glows at sunset.",
        address="Z Point Road",
        neighbourhood="Kemmangundi",
        city="Chikkamagaluru",
        latitude=13.5480,
        longitude=75.7560,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="view",
        price=5500,
        cleaning_fee=500,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=1,
        host=1,
        categories=("amazing-views", "cabins"),
        amenities=("Indoor fireplace", "Heating", "Garden", "Breakfast"),
    ),
    ListingSeed(
        title="Estate cabin in the Sakleshpur hills",
        summary="A rustic cabin on a cardamom and coffee estate, with waterfalls and tea "
        "gardens within an easy drive.",
        address="Hanbal Road",
        neighbourhood="Hanbal",
        city="Sakleshpur",
        latitude=12.9850,
        longitude=75.7600,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="cabin",
        price=6800,
        cleaning_fee=600,
        guests=4,
        bedrooms=2,
        beds=3,
        bathrooms=1,
        host=5,
        categories=("cabins", "farms", "countryside"),
        amenities=("Indoor fireplace", "Breakfast", "Free parking on premises", "BBQ grill"),
    ),
    ListingSeed(
        title="Infinity pool villa near Manjarabad Fort",
        summary="A glass-fronted villa with an infinity pool that seems to spill into the "
        "Western Ghats.",
        address="Manjarabad Fort Road",
        neighbourhood="Manjarabad",
        city="Sakleshpur",
        latitude=12.9300,
        longitude=75.7480,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="villa",
        price=22000,
        cleaning_fee=2000,
        guests=10,
        bedrooms=5,
        beds=6,
        bathrooms=5,
        host=4,
        categories=("amazing-pools", "amazing-views", "mansions"),
        amenities=(
            "Pool",
            "Hot tub",
            "Breakfast",
            "Patio or balcony",
            "Free parking on premises",
        ),
    ),
    ListingSeed(
        title="Riverside cottage on the Kabini backwaters",
        summary="Elephants come down to the water at dusk, and you watch from your own verandah.",
        address="Karapura Main Road",
        neighbourhood="Karapura",
        city="Kabini",
        latitude=11.9420,
        longitude=76.2860,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="tropical",
        price=8500,
        cleaning_fee=700,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=2,
        host=3,
        categories=("lakefront", "countryside"),
        amenities=("Lake access", "Breakfast", "Patio or balcony", "Air conditioning"),
    ),
    ListingSeed(
        title="Boutique safari room on the Kabini reservoir",
        summary="A stylish room with a private deck over the water, plus boat rides and guided "
        "jungle drives nearby.",
        address="Beechanahalli Road, N. Begur",
        neighbourhood="N. Begur",
        city="Kabini",
        latitude=11.9580,
        longitude=76.3260,
        property_type=PropertyType.HOTEL,
        room_type=RoomType.PRIVATE_ROOM,
        exterior="resort",
        price=12500,
        cleaning_fee=0,
        guests=2,
        bedrooms=1,
        beds=1,
        bathrooms=1,
        host=4,
        categories=("lakefront", "trending"),
        amenities=("Pool", "Breakfast", "Air conditioning", "Lake access", "Patio or balcony"),
    ),
    ListingSeed(
        title="Heritage townhouse near Mysuru Palace",
        summary="A restored home with carved rosewood doors and a rooftop that looks toward the "
        "lit-up palace on Sundays.",
        address="Kalidasa Road, Lakshmipuram",
        neighbourhood="Lakshmipuram",
        city="Mysuru",
        latitude=12.3075,
        longitude=76.6455,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="classic",
        price=9000,
        cleaning_fee=800,
        guests=6,
        bedrooms=3,
        beds=4,
        bathrooms=2,
        host=2,
        categories=("heritage-homes", "trending"),
        amenities=("Air conditioning", "Patio or balcony", "Washer", "Breakfast"),
    ),
    ListingSeed(
        title="Forest-edge farm stay near Bandipur",
        summary="A stone cottage on a millet farm at the edge of the forest, with peacocks in "
        "the fields at breakfast.",
        address="Mangala Village Road",
        neighbourhood="Mangala",
        city="Bandipur",
        latitude=11.6890,
        longitude=76.6060,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="cabin",
        price=7000,
        cleaning_fee=600,
        guests=5,
        bedrooms=2,
        beds=3,
        bathrooms=2,
        host=5,
        categories=("farms", "countryside"),
        amenities=("Breakfast", "Garden", "Free parking on premises", "BBQ grill"),
    ),
    ListingSeed(
        title="Boulder-view cabin in Ramanagara",
        summary="A glass cabin set among giant granite boulders, made for climbers, cyclists and "
        "sunset watchers.",
        address="Ramadevara Betta Road",
        neighbourhood="Ramadevara Betta",
        city="Ramanagara",
        latitude=12.7260,
        longitude=77.2750,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="view",
        price=4500,
        cleaning_fee=400,
        guests=3,
        bedrooms=1,
        beds=2,
        bathrooms=1,
        host=3,
        categories=("omg", "amazing-views"),
        amenities=("Patio or balcony", "Free parking on premises", "BBQ grill", "Breakfast"),
    ),
    ListingSeed(
        title="Farm villa with a pool off Kanakapura Road",
        summary="A whitewashed villa among coconut palms and vegetable beds, with a pool and "
        "cows for neighbours.",
        address="Kanakapura Road, Harohalli",
        neighbourhood="Harohalli",
        city="Kanakapura",
        latitude=12.6790,
        longitude=77.4640,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="villa",
        price=15000,
        cleaning_fee=1200,
        guests=10,
        bedrooms=4,
        beds=6,
        bathrooms=4,
        host=1,
        categories=("farms", "amazing-pools", "countryside"),
        amenities=(
            "Pool",
            "Garden",
            "BBQ grill",
            "Free parking on premises",
            "Breakfast",
            "Air conditioning",
        ),
    ),
    ListingSeed(
        title="Mango orchard farmhouse near Hosur",
        summary="A tiled farmhouse in a mango orchard, with fresh milk at dawn and a hammock "
        "under the trees.",
        address="Bagalur Road",
        neighbourhood="Bagalur",
        city="Hosur",
        latitude=12.8150,
        longitude=77.8480,
        property_type=PropertyType.HOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="classic",
        price=8000,
        cleaning_fee=700,
        guests=8,
        bedrooms=3,
        beds=4,
        bathrooms=2,
        host=5,
        categories=("farms", "countryside"),
        amenities=("Garden", "Free parking on premises", "BBQ grill", "Breakfast"),
    ),
    ListingSeed(
        title="River cottage near the Shivanasamudra falls",
        summary="A breezy cottage on the Kaveri, a short drive from the roar of the twin "
        "waterfalls.",
        address="Gaganachukki Road",
        neighbourhood="Shivanasamudra",
        city="Shivanasamudra",
        latitude=12.2880,
        longitude=77.1650,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="tropical",
        price=5000,
        cleaning_fee=500,
        guests=4,
        bedrooms=2,
        beds=2,
        bathrooms=1,
        host=3,
        categories=("countryside", "amazing-views"),
        amenities=("Garden", "Patio or balcony", "Free parking on premises", "Breakfast"),
    ),
    ListingSeed(
        title="Treehouse cabin in the BR Hills forest",
        summary="A stilted cabin high in the forest canopy, with gaur and hornbills often seen "
        "from the deck.",
        address="Yelandur Ghat Road",
        neighbourhood="Biligiri Rangana Hills",
        city="BR Hills",
        latitude=11.9940,
        longitude=77.1430,
        property_type=PropertyType.GUESTHOUSE,
        room_type=RoomType.ENTIRE_HOME,
        exterior="cabin",
        price=7500,
        cleaning_fee=600,
        guests=3,
        bedrooms=1,
        beds=2,
        bathrooms=1,
        host=5,
        categories=("treehouses", "cabins", "amazing-views"),
        amenities=("Breakfast", "Patio or balcony", "Heating", "Free parking on premises"),
    ),
]
