"""initial schema

Revision ID: 7312d727fc53
Revises:
Create Date: 2026-10-08 19:51:50.374732

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7312d727fc53"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amenities")),
        sa.UniqueConstraint("name", name=op.f("uq_amenities_name")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("google_sub", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("work", sa.String(length=120), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=False),
        sa.Column("lives_in", sa.String(length=120), nullable=True),
        sa.Column("is_superhost", sa.Boolean(), nullable=False),
        sa.Column("identity_verified_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "password_hash IS NOT NULL OR google_sub IS NOT NULL",
            name=op.f("ck_users_has_login_method"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "property_type",
            sa.Enum(
                "house",
                "apartment",
                "guesthouse",
                "hotel",
                name="propertytype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "room_type",
            sa.Enum(
                "entire_home",
                "private_room",
                "shared_room",
                name="roomtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("neighbourhood", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("google_place_id", sa.String(length=255), nullable=True),
        sa.Column("price_per_night", sa.Integer(), nullable=False),
        sa.Column("cleaning_fee", sa.Integer(), nullable=False),
        sa.Column("max_guests", sa.Integer(), nullable=False),
        sa.Column("bedrooms", sa.Integer(), nullable=False),
        sa.Column("beds", sa.Integer(), nullable=False),
        sa.Column("bathrooms", sa.Double(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "property_type IN ('house', 'apartment', 'guesthouse', 'hotel')", name="propertytype"
        ),
        sa.CheckConstraint(
            "property_type IN ('house', 'apartment', 'guesthouse', 'hotel')",
            name=op.f("ck_listings_propertytype"),
        ),
        sa.CheckConstraint(
            "room_type IN ('entire_home', 'private_room', 'shared_room')", name="roomtype"
        ),
        sa.CheckConstraint(
            "room_type IN ('entire_home', 'private_room', 'shared_room')",
            name=op.f("ck_listings_roomtype"),
        ),
        sa.CheckConstraint(
            "bedrooms >= 0 AND beds >= 1 AND bathrooms >= 0", name=op.f("ck_listings_rooms_valid")
        ),
        sa.CheckConstraint("cleaning_fee >= 0", name=op.f("ck_listings_cleaning_fee_non_negative")),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_listings_latitude_range")),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_listings_longitude_range")
        ),
        sa.CheckConstraint(
            "max_guests BETWEEN 1 AND 16", name=op.f("ck_listings_max_guests_range")
        ),
        sa.CheckConstraint("price_per_night > 0", name=op.f("ck_listings_price_positive")),
        sa.ForeignKeyConstraint(
            ["host_id"], ["users.id"], name=op.f("fk_listings_host_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
    )
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_listings_active_location",
            ["latitude", "longitude"],
            unique=False,
            sqlite_where=sa.text("archived_at IS NULL"),
        )
        batch_op.create_index(batch_op.f("ix_listings_city"), ["city"], unique=False)
        batch_op.create_index(batch_op.f("ix_listings_host_id"), ["host_id"], unique=False)

    op.create_table(
        "uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_uploads_size_positive")),
        sa.CheckConstraint("width > 0 AND height > 0", name=op.f("ck_uploads_dimensions_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_uploads_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_uploads_storage_key")),
        sa.UniqueConstraint("url", name=op.f("uq_uploads_url")),
    )
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uploads_user_id"), ["user_id"], unique=False)

    op.create_table(
        "wishlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_wishlists_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wishlists")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_wishlists_user_id_name")),
    )
    with op.batch_alter_table("wishlists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_wishlists_user_id"), ["user_id"], unique=False)

    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("guest_id", sa.Integer(), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("guests", sa.Integer(), nullable=False),
        sa.Column("nightly_rate", sa.Integer(), nullable=False),
        sa.Column("cleaning_fee", sa.Integer(), nullable=False),
        sa.Column("service_fee", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "confirmed",
                "cancelled",
                name="bookingstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'cancelled') = (cancelled_at IS NOT NULL)",
            name=op.f("ck_bookings_cancelled_at_matches"),
        ),
        sa.CheckConstraint("status IN ('confirmed', 'cancelled')", name="bookingstatus"),
        sa.CheckConstraint(
            "status IN ('confirmed', 'cancelled')", name=op.f("ck_bookings_bookingstatus")
        ),
        sa.CheckConstraint("check_out > check_in", name=op.f("ck_bookings_dates_order")),
        sa.CheckConstraint("guests BETWEEN 1 AND 16", name=op.f("ck_bookings_guests_range")),
        sa.CheckConstraint(
            "nightly_rate > 0 AND cleaning_fee >= 0 AND service_fee >= 0 AND total > 0",
            name=op.f("ck_bookings_amounts_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"], ["users.id"], name=op.f("fk_bookings_guest_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_bookings_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
    )
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookings_guest_id"), ["guest_id"], unique=False)
        batch_op.create_index(
            "ix_bookings_listing_dates", ["listing_id", "check_in", "check_out"], unique=False
        )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("guest_id", sa.Integer(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=False),
        sa.Column("guest_last_read_message_id", sa.Integer(), nullable=False),
        sa.Column("host_last_read_message_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["users.id"],
            name=op.f("fk_conversations_guest_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_conversations_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "listing_id", "guest_id", name=op.f("uq_conversations_listing_id_guest_id")
        ),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_guest_id"), ["guest_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversations_last_message_at"), ["last_message_at"], unique=False
        )

    op.create_table(
        "listing_amenities",
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("amenity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
            name=op.f("fk_listing_amenities_amenity_id_amenities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_amenities_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("listing_id", "amenity_id", name=op.f("pk_listing_amenities")),
    )
    with op.batch_alter_table("listing_amenities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_listing_amenities_amenity_id"), ["amenity_id"], unique=False
        )

    op.create_table(
        "listing_categories",
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_listing_categories_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_categories_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("listing_id", "category_id", name=op.f("pk_listing_categories")),
    )
    with op.batch_alter_table("listing_categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_listing_categories_category_id"), ["category_id"], unique=False
        )

    op.create_table(
        "listing_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_listing_images_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_images_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_images")),
    )
    with op.batch_alter_table("listing_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_listing_images_listing_id"), ["listing_id"], unique=False
        )

    op.create_table(
        "wishlist_items",
        sa.Column("wishlist_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_wishlist_items_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["wishlist_id"],
            ["wishlists.id"],
            name=op.f("fk_wishlist_items_wishlist_id_wishlists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("wishlist_id", "listing_id", name=op.f("pk_wishlist_items")),
    )
    with op.batch_alter_table("wishlist_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wishlist_items_listing_id"), ["listing_id"], unique=False
        )

    op.create_table(
        "guest_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_guest_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_guest_reviews_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest_reviews")),
        sa.UniqueConstraint("booking_id", name=op.f("uq_guest_reviews_booking_id")),
    )
    op.create_table(
        "listing_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("cleanliness", sa.Integer(), nullable=False),
        sa.Column("accuracy", sa.Integer(), nullable=False),
        sa.Column("check_in", sa.Integer(), nullable=False),
        sa.Column("communication", sa.Integer(), nullable=False),
        sa.Column("location", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accuracy BETWEEN 1 AND 5", name=op.f("ck_listing_reviews_accuracy_range")
        ),
        sa.CheckConstraint(
            "check_in BETWEEN 1 AND 5", name=op.f("ck_listing_reviews_check_in_range")
        ),
        sa.CheckConstraint(
            "cleanliness BETWEEN 1 AND 5", name=op.f("ck_listing_reviews_cleanliness_range")
        ),
        sa.CheckConstraint(
            "communication BETWEEN 1 AND 5", name=op.f("ck_listing_reviews_communication_range")
        ),
        sa.CheckConstraint(
            "location BETWEEN 1 AND 5", name=op.f("ck_listing_reviews_location_range")
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_listing_reviews_rating_range")),
        sa.CheckConstraint("value BETWEEN 1 AND 5", name=op.f("ck_listing_reviews_value_range")),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_listing_reviews_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_reviews")),
        sa.UniqueConstraint("booking_id", name=op.f("uq_listing_reviews_booking_id")),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
            name=op.f("fk_messages_sender_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_conversation_id_id", ["conversation_id", "id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_conversation_id_id")

    op.drop_table("messages")
    op.drop_table("listing_reviews")
    op.drop_table("guest_reviews")
    with op.batch_alter_table("wishlist_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wishlist_items_listing_id"))

    op.drop_table("wishlist_items")
    with op.batch_alter_table("listing_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listing_images_listing_id"))

    op.drop_table("listing_images")
    with op.batch_alter_table("listing_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listing_categories_category_id"))

    op.drop_table("listing_categories")
    with op.batch_alter_table("listing_amenities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listing_amenities_amenity_id"))

    op.drop_table("listing_amenities")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_last_message_at"))
        batch_op.drop_index(batch_op.f("ix_conversations_guest_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_index("ix_bookings_listing_dates")
        batch_op.drop_index(batch_op.f("ix_bookings_guest_id"))

    op.drop_table("bookings")
    with op.batch_alter_table("wishlists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wishlists_user_id"))

    op.drop_table("wishlists")
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_user_id"))

    op.drop_table("uploads")
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listings_host_id"))
        batch_op.drop_index(batch_op.f("ix_listings_city"))
        batch_op.drop_index(
            "ix_listings_active_location", sqlite_where=sa.text("archived_at IS NULL")
        )

    op.drop_table("listings")
    op.drop_table("users")
    op.drop_table("categories")
    op.drop_table("amenities")
    # ### end Alembic commands ###
