"use client";
import { useState } from "react";
import { Search } from "lucide-react";
import { Modal } from "@/components/ui/modal";
import styles from "./profiles.module.css";
import desktop from "./profile-editor-desktop.module.css";

const languages = ["English", "Afrikaans", "Albanian", "American Sign Language", "Arabic", "Armenian", "Assamese", "Azerbaijani", "Basque", "Belarusian", "Bengali", "Bosnian", "Brazilian Sign Language", "British Sign Language", "Bulgarian", "Burmese", "Catalan", "Chinese", "Chinese Sign Language", "Croatian", "Czech", "Danish", "Dutch", "Estonian", "Filipino", "Finnish", "French", "French Sign Language", "Galician", "Georgian", "German", "Greek", "Gujarati", "Haitian Creole", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Khmer", "Korean", "Kyrgyz", "Lao", "Latvian", "Lithuanian", "Macedonian", "Malay", "Malayalam", "Maltese", "Mandarin", "Marathi", "Norwegian", "Odia", "Persian", "Polish", "Portuguese", "Punjabi", "Romanian", "Russian", "Serbian", "Sign Language", "Slovak", "Slovenian", "Spanish", "Spanish Sign Language", "Swahili", "Swedish", "Tagalog", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Xhosa", "Zulu"];
export function LanguagesModal({ open = true, selected, onClose, onSave }: { open?: boolean; selected: string[]; onClose: () => void; onSave: (languages: string[]) => void }) {
  const [draft, setDraft] = useState(selected), [search, setSearch] = useState("");
  const choices = Array.from(new Set([...languages, ...selected])).sort((a,b) => a === "English" ? -1 : b === "English" ? 1 : a.localeCompare(b)).filter(language => language.toLowerCase().includes(search.trim().toLowerCase()));
  return <Modal open={open} onClose={() => { setDraft(selected); setSearch(""); onClose(); }} title="Languages you speak" presentation="profile" exitDuration={250} className={desktop.languagesPanel} backdropClassName={desktop.backdrop} footer={<div className={`${styles.modalActions} ${desktop.actions}`}><span className="sr-only" aria-live="polite">{draft.length}/10 selected</span><button type="button" className="dark-button" onClick={() => { setSearch(""); onSave(draft); }}>Save</button></div>}><div className={`${styles.languageDialog} ${desktop.languageDialog}`} data-profile-languages><h2>Languages you speak</h2><label className={styles.languageSearch}><Search size={20} aria-hidden="true" /><span className="sr-only">Search for a language</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search for a language" /></label><div className={styles.languageOptions}>{choices.map(language => <label key={language}><span>{language}</span><input type="checkbox" checked={draft.includes(language)} disabled={!draft.includes(language) && draft.length >= 10} onChange={event => setDraft(value => event.target.checked ? value.includes(language) || value.length >= 10 ? value : [...value, language] : value.filter(item => item !== language))} /></label>)}{!choices.length && <p className="muted">No languages match your search.</p>}</div></div></Modal>;
}
